### ISSUE TITLE
Requests blocked with status 403 (forbidden).

### ISSUE THREAD

**Issue by programmable-banking-community** [Investec-Developer-Community/.github#7]
Good morning,

I had a bit of a rogue script that hit the API many times (sorry :face_with_diagonal_mouth:)
Is it possible that a firewall is blocking my IP address now? I seem to be able to make the requests from a different IP.

I use one of these static IPs.
```
3.75.###.###
3.125.###.###
35.157.###.##
```
Would you mind investigating and releasing it again please :pray:

[Slack Message](https://investec-dev-com.slack.com/archives/C05MQQDUJ3E/p1705050992855299?thread_ts=1705050992.855299&cid=C05MQQDUJ3E)

**Comment by devinpearson** [comment]
Ive redacted the last parts of the ip addresses as its these pages are indexed
